!TestContext
description: Example of test profile for oc_config_validator

labels:
- FOO
- BAR

target:
  !Target
  target: "localhost:8080"
  tls_host_override: "target.com"
  gnmi_set_cooldown_secs: 2

init_configs:
- !InitConfig
  filename: init_config.json
  xpath: /system/config

tests:
- !TestCase
  name: "Get System Config"
  class_name: get.Get
  args:
    xpath: "system/config"

- !TestCase
  name: "Check System Config"
  class_name: get.GetJsonCheck
  args:
    xpath: "system/config"
    model: system.openconfig_system

- !TestCase
  name: "Check AAA State"
  class_name: get.GetJsonCheck
  args:
    xpath: "system/aaa/authentication/state"
    model: system.openconfig_system

- !TestCase
  name: "Compare Hostname Configured"
  class_name: get.GetCompare
  args:
    xpath: "system/config/hostname"
    want: "foo"

- !TestCase
  name: "Compare Domain Configured"
  class_name: get.GetCompare
  args:
    xpath: "system/config/domain-name"
    want: "foo.bar.com"

- !TestCase
  name: "Compare mgmt Interface state"
  class_name: get.GetCompare
  args:
    xpath: "interfaces/interface[name=mgmt]/state/enabled"
    want: true

- !TestCase
  name: "Compare mgmt Interface state JSON"
  class_name: get.GetCompare
  args:
    xpath: "interfaces/interface[name=mgmt]"
    want: {
      "openconfig-interfaces:state": {
        "enabled": true,
        "oper-status": "UP"}
      }

- !TestCase
  name: "Bad Compare mgmt Interface state JSON"
  class_name: get.GetCompare
  args:
    xpath: "interfaces/interface[name=mgmt]/state"
    want: {"openconfig-interfaces:enabled": false}

- !TestCase
  name: "Set Hostname"
  class_name: set.SetUpdate
  args:
    xpath: "system/config/hostname"
    value: "foobar"

- !TestCase
  name: "Compare System Config"
  class_name: get.GetJsonCheckCompare
  args:
    xpath: "system/config"
    model: system.openconfig_system
    want_json: {
      "openconfig-system:domain-name": "foo.bar.com",
      "openconfig-system:hostname": "foobar"
    }

- !TestCase
  name: "Bad model to compare System config"
  class_name: get.GetJsonCheckCompare
  args:
    xpath: "system/config"
    model: system.openconfig_system
    want_json: {
      "openconfig-system:domain-name": "foo.bar.com",
      "openconfig-system:hostname": "foobar"
    }

- !TestCase
  name: "Bad data to compare System config"
  class_name: get.GetJsonCheckCompare
  args:
    xpath: "system/config"
    model: system.openconfig_system
    want_json: {
      "openconfig-system:domain-name": "la.la.la.com",
      "openconfig-system:hostname": "lalala"
    }

- !TestCase
  name: "Set timezone with a valid Json blob"
  class_name: set.JsonCheckSetUpdate
  args:
    xpath: "system/clock/config"
    model: system.openconfig_system
    json_value: {
      "timezone-name": "Europe/London"
    }

- !TestCase
  name: "Compare Timezone"
  class_name: get.GetJsonCheckCompare
  args:
    xpath: "system/clock/config"
    model: system.openconfig_system
    want_json: {
      "openconfig-system:timezone-name": "Europe/London"
    }

- !TestCase
  name: "Set timezone with a valid Json blob"
  class_name: setget.SetGetJsonCheck
  args:
    xpath: "system/clock/config"
    model: system.openconfig_system
    json_value: {
      "openconfig-system:timezone-name": "Europe/Paris"
    }

- !TestCase
  name: "Set timezone with a valid Json blob, and check it is Zurich"
  class_name: setget.SetGetJsonCheckCompare
  args:
    xpath: "system/clock/config"
    model: system.openconfig_system
    json_value: {
      "openconfig-system:timezone-name": "Europe/Zurich"
    }

- !TestCase
  name: "Bad Set Clock Check State"
  class_name: config_state.SetConfigCheckState
  args:
    xpath: "system/clock"
    model: system.openconfig_system
    json_value: {
      "openconfig-system:timezone-name": "Europe/Paris"
    }
